server:
  port: 8083

spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:mariadb://mariadb:3306/customer_db?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework: DEBUG
    org.hibernate: DEBUG